FROM golang:latest as builder
ARG CGO_ENABLED=0

COPY ./ /root/src/
WORKDIR /root/src/
RUN go build -ldflags "-s -w -X main.version=$(git describe --tags --long --always)" -trimpath -o mosdns

FROM gcr.io/distroless/static-debian12:latest

COPY --from=builder /root/src/mosdns /usr/bin/mosdns

# 设置启动命令
ENTRYPOINT ["mosdns", "start", "-c", "/etc/mosdns/mosdns.yaml"]
